### ISSUE TITLE
Segfault on Fedora Linux with provided AppImage

### ISSUE THREAD

**Issue by Treeways** [black-sliver/PopTracker#111]
I get a segfault running the latest prerelease AppImage:

```
> ./PopTracker-0.25.8-x86_64.AppImage
PopTracker 0.25.8
Checking for update...
HTTP: connecting via https to api.github.com  for /repos/black-sliver/PopTracker/releases?per_page=8
Ui: Init SDL 2.0.20...
[1]    4585 segmentation fault (core dumped)  ./PopTracker-0.25.8-x86_64.AppImage
```

I'm running Fedora 38 on PopTracker 0.25.8.
I get no segfault building this from source with g++ 13.2.1.

**Comment by black-sliver** [comment]
Yep, the AppImage is currently broken on multiple distros (but not on all distros) . I wasn't able to figure out what the problem is, but it seems to happen when sdl video initializes.

**Comment by black-sliver** [comment]
It seems to still be broken in Fedora 38, but working in Fedora 39. Does that help you?

**Comment by Treeways** [comment]
So sorry for the delay! The latest version of PopTracker as of writing (0.29.0) works great on Fedora 40.

Thank you!
