### ISSUE TITLE
Location names containing `:` cannot be referenced in access rules

### ISSUE THREAD

**Issue by Mysteryem** [black-sliver/PopTracker#123]
I tried to add access rules to a location using the result of another location `"@ASLBBoss/Goal: Asylum Brain Tank"`.

Doing so prints the below error to standard output:
```Could not find location @ASLBBoss/Goal for access rule!```

Notably, the location appears to have been cut off at the `:`. I'm guessing this is because `:` is usually used to refer to a count of a consumable item: https://github.com/black-sliver/PopTracker/blob/f0321428c3d5f3d39e6ccd0dec56fd4454cfcea3/src/core/tracker.cpp#L735

**Comment by black-sliver** [comment]
Oh yeah, that's an interesting issue. Thanks for reporting. Gonna try to fix that in the next release by ignoring `:` for `@`
