### ISSUE TITLE
Missing dependency on Linux

### ISSUE THREAD

**Issue by marcmagus** [black-sliver/PopTracker#19]
Please add the package 'lua' to the listed dependencies in BUILD.md

**Comment by marcmagus** [comment]
This is incorrect, sorry, but downloading the .tar.gz it will not build because the lua submodule is not included. I had to git clone the tag release and update submodules to get something that would build properly. I'm not enough of a Makefile expert to know how, but it would be nice if you could use a system-installed lua if present instead. Or at least provide something in the release tarball that either includes or pulls the lua submodule.

**Comment by black-sliver** [comment]
Sorry for the late response. Glad you figured it out already :)

We build (most) dependencies from source to avoid the dependency mess (at this point I could complain for hours about using cmake or meson to try to build a static binary).

The releases' "Source code" is an automatic snapshot of the repository added by github. I'm not willing to copy in dependencies if they can be submoduled. I may add an additional release file for source for linux though (that includes the submodules dependencies) with the next release though.

**Comment by marcmagus** [comment]
Looking over things to suggest a solution I see that your build instructions do clearly say to download the source with `git clone --recurse-submodules` or download the submodules as well and I missed it. Clearly user error, so I apologize, although I do wonder if there's a way to make that stand out more.

I'm accustomed to "download the release tarball, extract, install deps using package manager, build" as my basic interaction, not "also download other stuff into the target directory" or "you have to git clone a tag". A release source file including the dependencies would do the job; I don't know how unique I am in tripping on this particular problem.

Just a quick aside, I really appreciate that you've taken on this project. It's a thing I've been threatening to do for about a year and I'm *thrilled* that someone beat me to it.

**Comment by black-sliver** [comment]
The build system is somewhat awkward because I want 1. use a specific lua version, 2. provide a static exe on windows, 3. build the windows exe cross-platform, 4. support wasm as a target in the future.

Automating a full release source tarball as part of the github action should be an easy fix. It should then be no problem if someone skips parts of the instructions.

> Just a quick aside, I really appreciate that you've taken on this project.

you are welcome :)

**Comment by black-sliver** [comment]
done. `..._full-source.tar.xz` is now automatically created for each tag :)
