### ISSUE TITLE
composite_toggle spec conflict

### ISSUE THREAD

**Issue by panicbit** [black-sliver/PopTracker#190]
The item spec currently specifies `composite_toggle` items to either be an object with the properties `["item_left", "item_right"]` *xor* (`anyOf`) an object with the keys `["images"]` ([see here](https://github.com/black-sliver/PopTracker/blob/master/schema/packs/items.json#L342-L422)).
This seems to be in conflict with the implementation, which expects all those fields to co-exist. In fact, it appears that it is required for the `images` array to exist for `item_left` and `item_right` to have any meaning ([see here](https://github.com/black-sliver/PopTracker/blob/b315c1cc719c95cd457cf5970259b017dbc54002/src/core/jsonitem.cpp#L89-L104)).

Am I maybe overlooking or misinterpreting something? 🤔

**Comment by black-sliver** [comment]
The schema seems to be wrong. Gonna ping @Cyb3RGER
