### ISSUE TITLE
Cannot import state on MacOS (v0.29)

### ISSUE THREAD

**Issue by TreZc0** [black-sliver/PopTracker#197]
Hey there. Found an interesting bug. 

Seems like the state exports works just fine, and exports valid json files.
However: Loading / Importing states will not work.
JSON files cannot be selected, effectively making an import impossible.

Dragging a json onto the tracker will open the import dialog, with the same issue.

<img width="559" alt="image" src="https://github.com/user-attachments/assets/13061099-8e5a-48cc-8afe-8ed1a4804fd8" />

**Comment by black-sliver** [comment]
Hm, when I checked the documentation for file selection on macos, it seemed like it's very limited, so this may very well be a problem/short-coming in the lib we are using not properly mapping the file type.

You could try the build here: <https://github.com/black-sliver/PopTracker/actions/runs/12286820742> which has an updated version of the lib.

If this does not fix it, please let me know and I am gonna remove the filter for macos altogether (i.e. accept any file, regardless of file type).

**Comment by TreZc0** [comment]
Hey, thanks for the build - sadly, this does not fix the issue unfortunately.

**Comment by black-sliver** [comment]
Can you try this build? https://github.com/black-sliver/PopTracker/actions/runs/12505839664

Random internet search result claims that `*.public.json` supposedly makes tinyfd map to the json UTType.

**Comment by TreZc0** [comment]
So sorry, completely forgot about it while on vacation. Glad you found a solution.
