### ISSUE TITLE
"toggle_badged" item type not implemented

### ISSUE THREAD

**Issue by ashkitten** [black-sliver/PopTracker#20]
this shows up in several minish cap tracker packs

**Comment by black-sliver** [comment]
Working on a bigger update right now, so i'll try to include that.

Can you tell me exactly how it works / what it does / how it's being called (and maybe link to a code snippet that uses it)?

**Comment by ashkitten** [comment]
i'm just a new user, but it seems it is a wrapper around any other item which adds a "badge" that toggles on right-click. i don't readily have a code snippet that includes it, but if you look in any minish cap emotracker pack it's there.

**Comment by black-sliver** [comment]
Sorry for taking so long :S

Looks like basically it should drawm an item over another item and one mouse button controls one item while the other mouse button controls the other item (similar to how `"composite_toggle"` works), but the top one is no separate item, but the `"toggle_badged"` itself.

Example of use (looking at the referenced PNGs explains how it's supposed to work):
https://github.com/cubesolver111/TMCMapTracker/blob/main/items/common.json#L209

I'll look into adding it this weekend and then we'll hopefully get a new release soon.
