### ISSUE TITLE
Readme links don't resolve correctly when opened via Notepad++

### ISSUE THREAD

**Issue by PoryGone** [black-sliver/PopTracker#25]
When double-clicking links from the `README.md` file in Notepad++, the `)` from the end of the hyperlink tag gets included as part of the link, so
```https://github.com/black-sliver/PopTracker/releases```
resolves as
```https://github.com/black-sliver/PopTracker/releases)```

This should be resolvable by adding a space between the actual link and the `)`.

**Comment by black-sliver** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7791 <- this?

**Comment by PoryGone** [comment]
Yep, that is the behaviour I see.

**Comment by black-sliver** [comment]
The current syntax is correct for markdown links afaict and the bug in np++ should have been fixed a while ago - if not maybe reopen a new issue over there?
