### ISSUE TITLE
macOS packs location inside APPBUNDLE

### ISSUE THREAD

**Issue by captcarl13** [black-sliver/PopTracker#28]
For macOS, packs need to be installed inside the app bundle. This is mentioned in the README.md, but vaguely worded.

1. From Finder, alt-click `poptracker.app`, and select `Show Package Contents`.
2. Navigate to `Contents/MacOS`. Full path should read `poptracker.app/Contents/MacOS`
3. Create a folder named `packs`, and drop content into that folder.

I've attached a photo of a Terminal highlighting this structure. Hope that helps to clarify some of that!
![Screen Shot 2022-09-30 at 6 04 39 PM](https://user-images.githubusercontent.com/867543/193362745-9cd790d8-a16f-4d83-bb6a-bc846f0e655e.png)

**Comment by black-sliver** [comment]
Sorry for the super late reply. I was hoping to resolve it before getting back to you. This is a documentation issue, not a usability issue.

You are not supposed to put packs into the app bundle (unless you want a custom app bundle). The sentence in the readme

> On macOS EXEDIR is inside the app bundle.

is supposed to mean "Please don't use EXEDIR as this sucks on macos, instead use another option."

I'm happy to take suggestions on how to update the readme to make that clear.

**Comment by captcarl13** [comment]
Interesting. The only way I was able to get it to work was by putting inside the appbundle. I haven't used the tracker since so I haven't experimented with other ways, unfortunately.
