### ISSUE TITLE
Poptracker doesn't open

### ISSUE THREAD

**Issue by MrPokemon11** [black-sliver/PopTracker#46]
Hello,
This is an issue I've had for a while, but I am only just now posting an Issue about it because I downloaded the latest version at it is still occurring. Whenever I open Poptracker, the program opens into my taskbar but does not open on any of my screens and displays a white box as the preview.
Demonstration: https://youtu.be/s96RYjlA6Dg
If there is any way for me to provide better information, like a log file, I would gladly do that if pointed to where that info can be found.
Thanks, MrPokemon11

**Comment by black-sliver** [comment]
Sorry for the late reply :S

You can either run the EXE from a Command Prompt to get live debug output, or enable the logfile in `%appdata%\PopTracker\PopTracker.json` by changing `"log": false` to `"log": true` while PopTracker is closed. It'll then create a file `%appdata%\PopTracker\log.txt`.

Three more things
1. you could try to set `"software_renderer": true` in said file
2. if the `PopTracker.json` does not exist that means you would have to run it from a Command Prompt
3. you could try to run an automated build from https://github.com/black-sliver/PopTracker/actions/workflows/binaries.yaml - they use a more standard version of the GUI library

**Comment by MrPokemon11** [comment]
problem solved, pos was set to very large negative numbers
