### ISSUE TITLE
PopTracker.json - "null" vs "false"

### ISSUE THREAD

**Issue by nivomi** [black-sliver/PopTracker#48]
If you change `hide_cleared_locations`, `hide_unreachable_locations` or `log` to 'true', when you return to the file, you might try changing them to 'false' to turn them off. Confusingly, this leaves these switches enabled, and they actually have to be set to 'null' to be turned back off. Better handling of this issue might reduce confusion and support inquiries.

**Comment by black-sliver** [comment]
I'm really bad at getting bad at Issues... sorry

There are two common mistakes:
1. changing anything in config while the application is running will get overwritten at exit.
2. `true` and `"true"` are two different things. If it's a string and not an actual boolean, it'll use the default.

I do think you probably hit mistake 1. because the default would be off for all 3 of those options.

In case of hide*, you can also toggle them using ctrl+h

**Comment by nivomi** [comment]
I don't think I've hit one or two, here - I've definitely run into 1 before and am aware of it already, and I've only been working with unquoted values.

STR:

1. Close PopTracker
2. Open %Appdata%/PopTracker/PopTracker.json in your text editor of choice
3. Ensure the following lines are present, exactly as typed:
`    "hide_cleared_locations": false,`
`    "hide_unreachable_locations": false,`
4. Save the file
5. Open PopTracker and refresh a pack (e.g. the witness AP pack)
6. Observe that only available locations are shown
![image](https://user-images.githubusercontent.com/651417/234643851-082891ea-8aec-47ef-9cc1-00dc3ac4702b.png)
7. Close and reopen PopTracker.json to ensure that it has not been clobbered
8. Observe that the above values are still present

For easier reproduction, I have also uploaded the contents of my PopTracker.json here: https://pastebin.com/nPDB2fYa

and here's a screen recording demonstrating the issue: https://youtu.be/JLS4YvMtyDY

Let me know if there's anything further I can provide regarding this issue.

**Comment by black-sliver** [comment]
Oh, I see the bug now: there is a mistake when applying hide_* from config on start. If it's valid (bool) it'll correctly apply the override, but not the actual value, resulting in always being hidden. Thanks for reporting! :)

This should be specific to hide_* though and should not happen with log.

**Comment by nivomi** [comment]
I've re-tested and you're right - this doesn't impact log. Sorry about that!
