### ISSUE TITLE
Assets loading from config directory

### ISSUE THREAD

**Issue by MegaPramuk** [black-sliver/PopTracker#51]
Hello there!
First of all, I want to mention that I use GNU/Linux and while theoretically it applies to all versions, I believe it's practically only this since MacOS and Windows have compiled releases.
Yesterday, I wanted to play a multiworld with some people over Discord and I was suggested using this.
Thing is, when I launched it, the UI buttons didn't load.

![image](https://github.com/black-sliver/PopTracker/assets/9656711/e30cde91-1d1b-4dad-a5f2-7b973c25f861)

Having the assets in the same directory as the binary fixes it.
Now, later I found out (or rather was told) that this is mentioned in the BUILD.md and I must have skimmed over it.
But since it creates a ~/.config/PopTracker (and I assume a folder inside %APPDATA% as well), why not load the assets from there so it doesn't matter what folder one is in?
I have a specific way of organising my files and folders and this one doesn't really fit without always being in a specific directory. 
For example, I like to have all my software I compiled myself in ~/bin (part of $PATH) so that I can just call it from anywhere which just isn't feasible as of right now because it doesn't load any assets and can't even connect it to AP if it hasn't loaded the specific file.

EDIT: Reason why I'm in the build directory in the screenshot is simple. It's a habit of mine to go inside the build folder and run it from there for the first time before I actually include it into my system.

**Comment by black-sliver** [comment]
I want to say, the correct folder would probably be ~/.local/share/PopTracker (or /usr/share for system-wide install). We can probably add those as search path for assets, but it's not super transparent to the user how to properly install it. I'm open for suggestions.

The way it's currently though to be used is that you drop both the binary and the assets into /opt/PopTracker or any folder in ~ and create a .desktop to that. I was hoping to get AppImage, maybe Flatpak and maybe .deb to auto-build, but never found the time - we do have someone building AppImages over in the Discord though.

**Comment by MegaPramuk** [comment]
>but it's not super transparent to the user how to properly install it

I mean, it could be explained in the README.md that it looks at those paths for the assets, similar to how it's already done for the packs.

> I'm open for suggestions.

Alternatively, make it an option in the PopTracker.json to specify a path to load the assets from.
Something like `"assets_path": "assets"`. 
Perhaps explain that you can change stuff in said file (or that it gets created at first start-up at all) in the README.md as well.

>and create a .desktop to that.

Well, that wouldn't help me any way at all either since I don't use any DE so .desktop files would be pointless for me as well (not speaking for the general public though obviously).
I either run my software with the shell or (more often) via gmrun so that a shell doesn't get unnecessarily occupied.

**Comment by black-sliver** [comment]
Until this is resolved, you can put the assets folder into ~/PopTracker, which is also the default folder for pack installation, and functions as user override (i.e. has higher priority).

**Comment by black-sliver** [comment]
Hm, there was a bug that would not correctly add `~/PopTracker/assets` as search path when running from pwd=~.

It's fixed in https://github.com/black-sliver/PopTracker/commit/a888623b74d508d71e0096b5d835286a836ea370 and the next release should happen soon :tm:

**Comment by MegaPramuk** [comment]
Since I could confirm that poptracker can now be run from anywhere and load anything correctly, I guess this can be closed as solved then since it now does what I asked about, having a central folder to load assets from rather than having it start from the same directory the assets are in.
Thank you very much!
